def loadSkipConfigMobile(BRANCHES):

    BRANCHES['fx-team']['platforms']['android-api-9']['ubuntu64_vm_large']['skipconfig'] = {
                                                                                            ('opt', 'crashtest-1'): (10, 3400),
                                                                                            ('opt', 'crashtest-2'): (10, 3400),
                                                                                            ('opt', 'jsreftest-1'): (10, 3400),
                                                                                            ('opt', 'jsreftest-2'): (10, 3400),
                                                                                            ('opt', 'jsreftest-3'): (10, 3400),
                                                                                            ('opt', 'jsreftest-4'): (10, 3400),
                                                                                            ('opt', 'jsreftest-5'): (10, 3400),
                                                                                            ('opt', 'jsreftest-6'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-1'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-10'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-11'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-12'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-13'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-14'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-15'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-16'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-2'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-3'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-4'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-5'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-7'): (10, 3400),
                                                                                            ('opt', 'plain-reftest-9'): (10, 3400),
                                                                                           }
    BRANCHES['fx-team']['platforms']['android-api-9']['ubuntu64_vm_mobile']['skipconfig'] = {
                                                                                             ('opt', 'mochitest-1'): (10, 3400),
                                                                                             ('opt', 'mochitest-10'): (10, 3400),
                                                                                             ('opt', 'mochitest-11'): (10, 3400),
                                                                                             ('opt', 'mochitest-12'): (10, 3400),
                                                                                             ('opt', 'mochitest-14'): (10, 3400),
                                                                                             ('opt', 'mochitest-16'): (10, 3400),
                                                                                             ('opt', 'mochitest-2'): (10, 3400),
                                                                                             ('opt', 'mochitest-3'): (10, 3400),
                                                                                             ('opt', 'mochitest-5'): (10, 3400),
                                                                                             ('opt', 'mochitest-6'): (10, 3400),
                                                                                             ('opt', 'mochitest-7'): (10, 3400),
                                                                                             ('opt', 'mochitest-8'): (10, 3400),
                                                                                             ('opt', 'mochitest-gl-1'): (10, 3400),
                                                                                             ('opt', 'mochitest-gl-2'): (10, 3400),
                                                                                             ('opt', 'mochitest-gl-3'): (10, 3400),
                                                                                             ('opt', 'mochitest-gl-4'): (10, 3400),
                                                                                             ('opt', 'robocop-4'): (10, 3400),
                                                                                             ('opt', 'xpcshell-1'): (10, 3400),
                                                                                             ('opt', 'xpcshell-2'): (10, 3400),
                                                                                             ('opt', 'xpcshell-3'): (10, 3400),
                                                                                            }

    BRANCHES['mozilla-inbound']['platforms']['android-api-9']['ubuntu64_vm_large']['skipconfig'] = {
                                                                                                    ('opt', 'crashtest-1'): (10, 3400),
                                                                                                    ('opt', 'crashtest-2'): (10, 3400),
                                                                                                    ('opt', 'jsreftest-1'): (10, 3400),
                                                                                                    ('opt', 'jsreftest-2'): (10, 3400),
                                                                                                    ('opt', 'jsreftest-3'): (10, 3400),
                                                                                                    ('opt', 'jsreftest-4'): (10, 3400),
                                                                                                    ('opt', 'jsreftest-5'): (10, 3400),
                                                                                                    ('opt', 'jsreftest-6'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-1'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-10'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-11'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-12'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-13'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-14'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-15'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-16'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-2'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-3'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-4'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-5'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-7'): (10, 3400),
                                                                                                    ('opt', 'plain-reftest-9'): (10, 3400),
                                                                                                   }
    BRANCHES['mozilla-inbound']['platforms']['android-api-9']['ubuntu64_vm_mobile']['skipconfig'] = {
                                                                                                     ('opt', 'mochitest-1'): (10, 3400),
                                                                                                     ('opt', 'mochitest-10'): (10, 3400),
                                                                                                     ('opt', 'mochitest-11'): (10, 3400),
                                                                                                     ('opt', 'mochitest-12'): (10, 3400),
                                                                                                     ('opt', 'mochitest-14'): (10, 3400),
                                                                                                     ('opt', 'mochitest-16'): (10, 3400),
                                                                                                     ('opt', 'mochitest-2'): (10, 3400),
                                                                                                     ('opt', 'mochitest-3'): (10, 3400),
                                                                                                     ('opt', 'mochitest-5'): (10, 3400),
                                                                                                     ('opt', 'mochitest-6'): (10, 3400),
                                                                                                     ('opt', 'mochitest-7'): (10, 3400),
                                                                                                     ('opt', 'mochitest-8'): (10, 3400),
                                                                                                     ('opt', 'mochitest-gl-1'): (10, 3400),
                                                                                                     ('opt', 'mochitest-gl-2'): (10, 3400),
                                                                                                     ('opt', 'mochitest-gl-3'): (10, 3400),
                                                                                                     ('opt', 'mochitest-gl-4'): (10, 3400),
                                                                                                     ('opt', 'robocop-4'): (10, 3400),
                                                                                                     ('opt', 'xpcshell-1'): (10, 3400),
                                                                                                     ('opt', 'xpcshell-2'): (10, 3400),
                                                                                                     ('opt', 'xpcshell-3'): (10, 3400),
                                                                                                    }

