releaseConfig['AllRecipients']      = ['<release+releasespam@mozilla.com>',]
releaseConfig['ImportantRecipients']      = ['<release+releasespam@mozilla.com>',]
releaseConfig['l10nRepoPath']        = 'users/prepr-ffxbld'
releaseConfig['hgUsername']          = 'prepr-ffxbld'
releaseConfig['stagingServer']       = 'preproduction-stage.srv.releng.scl3.mozilla.com'
releaseConfig['ausServerUrl']        = 'http://preproduction-stage.srv.releng.scl3.mozilla.com'
releaseConfig['partnersRepoPath']    = 'users/prepr-ffxbld/partner-repacks'
releaseConfig['tuxedoServerUrl']     = 'https://tuxedo.stage.mozilla.com/api/'
releaseConfig['enable_repo_setup']   = True
releaseConfig['messagePrefix']       = '[preprod-release] '
releaseConfig['userRepoRoot']        = 'users/prepr-ffxbld'
releaseConfig['ftpServer']           = 'preproduction-stage.srv.releng.scl3.mozilla.com'
releaseConfig['disableBouncerEntries']    = True
