releaseConfig['ImportantRecipients']      = ['release@mozilla.com',]
releaseConfig['l10nRepoPath']        = 'users/prepr-ffxbld'
releaseConfig['l10nChunks']          = 2
releaseConfig['hgUsername']          = 'prepr-ffxbld'
releaseConfig['cvsroot']             = ':ext:stgbld@cvs.mozilla.org:/cvsroot'
releaseConfig['stagingServer']       = 'preproduction-stage.srv.releng.scl3.mozilla.com'
releaseConfig['ausServerUrl']        = 'http://preproduction-stage.srv.releng.scl3.mozilla.com'
releaseConfig['partnersRepoPath']    = 'users/prepr-ffxbld/partner-repacks'
releaseConfig['tuxedoServerUrl']     = 'https://tuxedo.stage.mozilla.com/api/'
releaseConfig['enable_repo_setup']   = True
releaseConfig['commitPatcherConfig'] = False # TODO: toggle when CVS mirror is live
releaseConfig['messagePrefix']       = '[preprod-release] '
releaseConfig['userRepoRoot']        = 'users/prepr-ffxbld'
releaseConfig['ftpServer']           = 'preproduction-stage.srv.releng.scl3.mozilla.com'
releaseConfig['disableBouncerEntries']    = True
releaseConfig['enableSigningAtBuildTime'] = False
releaseConfig['enablePartialMarsAtBuildTime'] = False
